#!/bin/bash

# Create a list of all staged files
# filter out deleted files
STAGED_FILES=$(git diff --name-only --cached --diff-filter=d)

# Pass that list of files to the following commands
if [ -n "$STAGED_FILES" ]; then
    # Run Pint
    vendor/bin/pint $STAGED_FILES
fi
